// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0EH5c1LvbU8QUqw4U4VZI6-O1Q7WJ8Y',
    appId: '1:300581504145:web:89ff397d64775b5b6dab30',
    messagingSenderId: '300581504145',
    projectId: 'madd-10aa4',
    authDomain: 'madd-10aa4.firebaseapp.com',
    storageBucket: 'madd-10aa4.appspot.com',
    measurementId: 'G-2CNC5C7608',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNCT9KI3ty0puJuWxFcsWv35m_W9t3Dk',
    appId: '1:300581504145:android:5da2cafb3e703b0f6dab30',
    messagingSenderId: '300581504145',
    projectId: 'madd-10aa4',
    storageBucket: 'madd-10aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6nr2_dvmSSRdG1u4rxvI8uScFN81-Wi0',
    appId: '1:300581504145:ios:2338ded5d10f2d236dab30',
    messagingSenderId: '300581504145',
    projectId: 'madd-10aa4',
    storageBucket: 'madd-10aa4.appspot.com',
    iosBundleId: 'com.example.lab5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6nr2_dvmSSRdG1u4rxvI8uScFN81-Wi0',
    appId: '1:300581504145:ios:2338ded5d10f2d236dab30',
    messagingSenderId: '300581504145',
    projectId: 'madd-10aa4',
    storageBucket: 'madd-10aa4.appspot.com',
    iosBundleId: 'com.example.lab5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0EH5c1LvbU8QUqw4U4VZI6-O1Q7WJ8Y',
    appId: '1:300581504145:web:4d7c4fcba05e30fb6dab30',
    messagingSenderId: '300581504145',
    projectId: 'madd-10aa4',
    authDomain: 'madd-10aa4.firebaseapp.com',
    storageBucket: 'madd-10aa4.appspot.com',
    measurementId: 'G-WNQE00BJMQ',
  );
}
